set(SRC_FILES
    App.cpp
        AppUtil.cpp
        AnimatedObjects.cpp
        MainCharacter.cpp
        Objects.cpp
        PhaseResourceManager.cpp
        WoodBox.cpp
        Bounce.cpp
        Balloon.cpp
        Cloud.cpp
)

set(INCLUDE_FILES
    App.hpp
        AppUtil.hpp
        AnimatedObjects.hpp
        BackgroundImage.hpp
        InvisibleWall.hpp
        Main_Character.hpp
        Objects.hpp
        PhaseResourceManager.hpp
        Trap.hpp
        Bounce.hpp
        Balloon.hpp
        WoodBox.hpp
        Cloud.hpp
)

set(TEST_FILES
)
